### ISSUE TITLE
Login and Registration

### ISSUE THREAD

**Issue by ajrbyers** [ajrbyers/pancea#1]
Login and Registration of users should be handled via ORCiD

- [x] Pull ORCiD utils from Janeway
- [x] Add registration via ORCiD
- [x] Add login via ORCiD

**Comment by Protohedgehog** [comment]
Could we have a second OAuth layer too, so people can attach their Twitter/LinkedIn etc. profiles too..? Or is that too complicated at this step?

**Comment by ajrbyers** [comment]
For initial step I thought we should stick to ORCiD as we also want to use it to authenticate a user as well as authorize them for login

**Comment by Protohedgehog** [comment]
OK, yep sounds perfect!
